### PR TITLE
[bt#22420] Avoid side effects when resetting discounts

### PR DESCRIPTION
**Pull request by BT-avoss**
<div> Links to Odoo: </div> <ul>
<li><a target="_blank" href="https://braintec.com/web#view_type=form&model=helpdesk.ticket&id=22420">[bt#22420] AW: Odoo Gutschrift geht nicht</a></li>
</ul>
<div>Affected Modules:</div>
<table><thead><tr><th>Module</th><th>Ext</th></tr></thead>
<tr><td>account_invoice_triple_discount</td><td>.py</td></tr>
</tbody></table>

### CODE REVIEW

**Comment by BT-avoss** [comment]
This fixes what is basically a dirty trick by OCA for their triple discount module. They temporarily aggregate all three discounts into the standard discount field so that Odoo handles the actual discounted price calculation and afterwards they split it back up again into three fields.

This, however, caused some trouble for Protel as they've used a write() which triggered some other calculations (currency conversions). Now, a direct UPDATE in the database is used instead to avoid any side-effects.

**Review by BT-tbaechle — COMMENTED** [review]
The code looks good, however I am always reluctant to write directly into the DB bypassing the entire ORM. Might it be an alternative to pass a context parameter to the write call and don't execute the other calculations if it is present?

**Comment by BT-avoss** [comment]
Thanks for the review!
Yes, context would be nicer, but it is very difficult here, as we'd need to patch one of the core methods to check for that context. I don't know what is cleaner: patching or bypassing ORM. I prefer bypassing the ORM in this case.

**Review by BT-tbaechle — APPROVED** [review]
Okay then. I assumed the calculation triggered would be something customer specific and could easily use the context.

**Pull request merged**
